type Statistics = {
  cpuUsage: number;
  ramUsage: number;
  storageUsage: number;
};

type StaticData = {
  totalStorage: number;
  cpuModel: string;
  totalMemoryGB: number;
};

type BackendTruthRegistry = import("./src/electron/backend/models.js").BackendTruthRegistry;
type BackendBootstrapStatus = import("./src/electron/backend/models.js").BackendBootstrapStatus;
type Mapa = import("./src/electron/backend/models.js").Mapa;
type UpsertMapInput = import("./src/electron/modules/maps/domain/map.js").UpsertMapInput;
type CreateEscenarioInput = import("./src/electron/modules/scenarios/domain/scenario.js").CreateEscenarioInput;
type CreateTipoEscenarioInput = import("./src/electron/modules/scenarios/domain/scenario.js").CreateTipoEscenarioInput;
type CreateSimulacionInput = import("./src/electron/modules/simulations/domain/simulation.js").CreateSimulacionInput;
type CreateTipoSimulacionInput = import("./src/electron/modules/simulations/domain/simulation.js").CreateTipoSimulacionInput;
type Escenario = import("./src/electron/backend/models.js").Escenario;
type TipoEscenario = import("./src/electron/backend/models.js").TipoEscenario;
type Simulacion = import("./src/electron/backend/models.js").Simulacion;
type TipoSimulacion = import("./src/electron/backend/models.js").TipoSimulacion;
type LegacyVisualizerMapResponse = import("./src/electron/modules/maps/interfaces/legacyAdapter.js").LegacyVisualizerMapResponse;
type MapImportPayload = import("./src/electron/modules/imports/domain/importJob.js").MapImportPayload;
type ImportJobResult = import("./src/electron/modules/imports/domain/importJob.js").ImportJobResult;
type Produccion = import("./src/electron/backend/models.js").Produccion;
type CreateProduccionInput = import("./src/electron/modules/production/domain/production.js").CreateProduccionInput;
type Proyecto = import("./src/electron/backend/models.js").Proyecto;
type Unidades = import("./src/electron/backend/models.js").Unidades;
type Capa = import("./src/electron/backend/models.js").Capa;
type Pozo = import("./src/electron/backend/models.js").Pozo;
type PozoCapa = import("./src/electron/backend/models.js").PozoCapa;
type CreateProyectoInput = import("./src/electron/modules/core-data/domain/coreData.js").CreateProyectoInput;
type CreateUnidadesInput = import("./src/electron/modules/core-data/domain/coreData.js").CreateUnidadesInput;
type CreateCapaInput = import("./src/electron/modules/core-data/domain/coreData.js").CreateCapaInput;
type CreatePozoInput = import("./src/electron/modules/core-data/domain/coreData.js").CreatePozoInput;
type CreatePozoCapaInput = import("./src/electron/modules/core-data/domain/coreData.js").CreatePozoCapaInput;
type ValorEscenario = import("./src/electron/backend/models.js").ValorEscenario;
type TipoEstadoPozo = import("./src/electron/backend/models.js").TipoEstadoPozo;
type SetEstadoPozos = import("./src/electron/backend/models.js").SetEstadoPozos;
type SetEstadoPozosDetalle = import("./src/electron/backend/models.js").SetEstadoPozosDetalle;
type GrupoVariable = import("./src/electron/backend/models.js").GrupoVariable;
type Variable = import("./src/electron/backend/models.js").Variable;
type ElipseVariable = import("./src/electron/backend/models.js").ElipseVariable;
type ElipseValor = import("./src/electron/backend/models.js").ElipseValor;
type CreateValorEscenarioInput = import("./src/electron/modules/scenario-values/domain/scenarioValue.js").CreateValorEscenarioInput;
type CreateTipoEstadoPozoInput = import("./src/electron/modules/well-states/domain/wellStates.js").CreateTipoEstadoPozoInput;
type CreateSetEstadoPozosInput = import("./src/electron/modules/well-states/domain/wellStates.js").CreateSetEstadoPozosInput;
type CreateSetEstadoPozosDetalleInput = import("./src/electron/modules/well-states/domain/wellStates.js").CreateSetEstadoPozosDetalleInput;
type CreateGrupoVariableInput = import("./src/electron/modules/variables/domain/variables.js").CreateGrupoVariableInput;
type CreateVariableInput = import("./src/electron/modules/variables/domain/variables.js").CreateVariableInput;
type CreateElipseVariableInput = import("./src/electron/modules/ellipse/domain/ellipse.js").CreateElipseVariableInput;
type CreateElipseValorInput = import("./src/electron/modules/ellipse/domain/ellipse.js").CreateElipseValorInput;

type EventPayloadMapping = {
  statistics: Statistics;
  getStaticData: StaticData;
  backendGetTruthRegistry: BackendTruthRegistry;
  backendInitSchema: BackendBootstrapStatus;
  backendSeedInitialData: BackendBootstrapStatus;
  backendGetBootstrapStatus: BackendBootstrapStatus;
  mapsGetByLayer: Mapa | null;
  mapsUpsert: Mapa;
  legacyVisualizerGetMap: LegacyVisualizerMapResponse | null;
  scenarioTypeCreate: TipoEscenario;
  scenarioTypeList: TipoEscenario[];
  scenarioCreate: Escenario;
  scenarioListByProject: Escenario[];
  simulationTypeCreate: TipoSimulacion;
  simulationTypeList: TipoSimulacion[];
  simulationCreate: Simulacion;
  simulationListByProject: Simulacion[];
  importMapsDryRun: ImportJobResult;
  importMapsCommit: ImportJobResult;
  productionCreate: Produccion;
  productionListByProject: Produccion[];
  scenarioValueCreate: ValorEscenario;
  scenarioValueListByEscenario: ValorEscenario[];
  wellStateTypeCreate: TipoEstadoPozo;
  wellStateTypeList: TipoEstadoPozo[];
  wellStateSetCreate: SetEstadoPozos;
  wellStateSetListByProject: SetEstadoPozos[];
  wellStateSetDetailCreate: SetEstadoPozosDetalle;
  wellStateSetDetailList: SetEstadoPozosDetalle[];
  grupoVariableCreate: GrupoVariable;
  grupoVariableList: GrupoVariable[];
  variableCreate: Variable;
  variableListByUnidades: Variable[];
  ellipseVariableCreate: ElipseVariable;
  ellipseVariableList: ElipseVariable[];
  ellipseValueCreate: ElipseValor;
  ellipseValueListByProject: ElipseValor[];
  coreUnidadesCreate: Unidades;
  coreUnidadesListByProject: Unidades[];
  coreProyectoCreate: Proyecto;
  coreProyectoList: Proyecto[];
  coreCapaCreate: Capa;
  coreCapaListByProject: Capa[];
  corePozoCreate: Pozo;
  corePozoListByProject: Pozo[];
  corePozoCapaCreate: PozoCapa;
  corePozoCapaListByProject: PozoCapa[];
};

type UnsuscribeFunction = () => void;

interface Window {
  electron: {
    subscribeStatistics: (
      callback: (statistics: Statistics) => void
    ) => UnsuscribeFunction;
    getStaticData: () => Promise<StaticData>;
    backendGetTruthRegistry: () => Promise<BackendTruthRegistry>;
    backendInitSchema: () => Promise<BackendBootstrapStatus>;
    backendSeedInitialData: () => Promise<BackendBootstrapStatus>;
    backendGetBootstrapStatus: () => Promise<BackendBootstrapStatus>;
    mapsGetByLayer: (params: { capaId: string; variableMapaId?: string }) => Promise<Mapa | null>;
    mapsUpsert: (payload: UpsertMapInput) => Promise<Mapa>;
    legacyVisualizerGetMap: (params: { capaId: string; variableMapaId?: string }) => Promise<LegacyVisualizerMapResponse | null>;
    scenarioTypeCreate: (payload: CreateTipoEscenarioInput) => Promise<TipoEscenario>;
    scenarioTypeList: () => Promise<TipoEscenario[]>;
    scenarioCreate: (payload: CreateEscenarioInput) => Promise<Escenario>;
    scenarioListByProject: (payload: { proyectoId: string }) => Promise<Escenario[]>;
    simulationTypeCreate: (payload: CreateTipoSimulacionInput) => Promise<TipoSimulacion>;
    simulationTypeList: () => Promise<TipoSimulacion[]>;
    simulationCreate: (payload: CreateSimulacionInput) => Promise<Simulacion>;
    simulationListByProject: (payload: { proyectoId: string }) => Promise<Simulacion[]>;
    importMapsDryRun: (payload: MapImportPayload) => Promise<ImportJobResult>;
    importMapsCommit: (payload: MapImportPayload) => Promise<ImportJobResult>;
    productionCreate: (payload: CreateProduccionInput) => Promise<Produccion>;
    productionListByProject: (payload: { proyectoId: string }) => Promise<Produccion[]>;
    scenarioValueCreate: (payload: CreateValorEscenarioInput) => Promise<ValorEscenario>;
    scenarioValueListByEscenario: (payload: { escenarioId: string }) => Promise<ValorEscenario[]>;
    wellStateTypeCreate: (payload: CreateTipoEstadoPozoInput) => Promise<TipoEstadoPozo>;
    wellStateTypeList: () => Promise<TipoEstadoPozo[]>;
    wellStateSetCreate: (payload: CreateSetEstadoPozosInput) => Promise<SetEstadoPozos>;
    wellStateSetListByProject: (payload: { proyectoId: string }) => Promise<SetEstadoPozos[]>;
    wellStateSetDetailCreate: (payload: CreateSetEstadoPozosDetalleInput) => Promise<SetEstadoPozosDetalle>;
    wellStateSetDetailList: (payload: { setEstadoPozosId: string }) => Promise<SetEstadoPozosDetalle[]>;
    grupoVariableCreate: (payload: CreateGrupoVariableInput) => Promise<GrupoVariable>;
    grupoVariableList: () => Promise<GrupoVariable[]>;
    variableCreate: (payload: CreateVariableInput) => Promise<Variable>;
    variableListByUnidades: (payload: { unidadesId: string }) => Promise<Variable[]>;
    ellipseVariableCreate: (payload: CreateElipseVariableInput) => Promise<ElipseVariable>;
    ellipseVariableList: () => Promise<ElipseVariable[]>;
    ellipseValueCreate: (payload: CreateElipseValorInput) => Promise<ElipseValor>;
    ellipseValueListByProject: (payload: { proyectoId: string }) => Promise<ElipseValor[]>;
    coreUnidadesCreate: (payload: CreateUnidadesInput) => Promise<Unidades>;
    coreUnidadesListByProject: (payload: { proyectoId: string }) => Promise<Unidades[]>;
    coreProyectoCreate: (payload: CreateProyectoInput) => Promise<Proyecto>;
    coreProyectoList: () => Promise<Proyecto[]>;
    coreCapaCreate: (payload: CreateCapaInput) => Promise<Capa>;
    coreCapaListByProject: (payload: { proyectoId: string }) => Promise<Capa[]>;
    corePozoCreate: (payload: CreatePozoInput) => Promise<Pozo>;
    corePozoListByProject: (payload: { proyectoId: string }) => Promise<Pozo[]>;
    corePozoCapaCreate: (payload: CreatePozoCapaInput) => Promise<PozoCapa>;
    corePozoCapaListByProject: (payload: { proyectoId: string }) => Promise<PozoCapa[]>;
  };
}
